### ISSUE TITLE
Uncaught TypeError: (intermediate value)(...) is not a function

### ISSUE THREAD

**Issue by doup** [rstacruz/unorphan#5]
I think that this commit has added a bug: 5ec98388b2534f14dfb97295d91796e2917a4802
I've checked with the previous module definition and it works.

When concatenating, if the unorphan file is put at the end it works. :-/

**Comment by rstacruz** [comment]
do you have a test case i can see?

**Comment by rstacruz** [comment]
also, will changing `void` on line 1 to `;` work?

**Comment by rstacruz** [comment]
and what's your setup? the issue here is that this will fail:

``` js
(function() {
  document.body.innerHTML += '1'
}())
(function() {
  document.body.innerHTML += '2'
}())
/* Uncaught TypeError: (intermediate value)(...) is not a function */
```

but adding `void` should fix it:

``` js
(function() {
  document.body.innerHTML += '1'
}())
void (function() {
  document.body.innerHTML += '2'
}())
```

I'm surprised it didn't work on your setup.

**Comment by doup** [comment]
Adding a `;` at the end of the file fixes it. The issue is the one you point in the last post. Only that you missed the other option, when unorphan is **before** another lib. Here `void` does nothing. :wink: 

``` js
void (function() {
  // Unorphan
  document.body.innerHTML += '1'
}())
(function() {
  // Another lib
  document.body.innerHTML += '2'
}())
```

**Comment by rstacruz** [comment]
ah..  `¯\_(ツ)_/¯` damn
